### ISSUE TITLE
Resource Controller HTTP methods

### ISSUE THREAD

**Issue by BugsBunnyBR** [vapor/documentation#112]
Hi, I am trying to figure out what are the HTTP methods used for each action in a Resource controller as shown [here](https://vapor.github.io/documentation/guide/controllers.html)
 
```
  var index: Multiple?
    var store: Multiple?
    var show: Item?
    var replace: Item?
    var modify: Item?
    var destroy: Item?
    var clear: Multiple?
    var aboutItem: Item?
    var aboutMultiple: Multiple?
```
So `index` and `show` uses GET. `destroy` uses DELETE, but how about the others? The documentation could have something like

```
  var index: Multiple?  // GET
    var store: Multiple?
    var show: Item?  // GET
    var replace: Item?
    var modify: Item?
    var destroy: Item? // DELETE
    var clear: Multiple?
    var aboutItem: Item?
    var aboutMultiple: Multiple?
```

or a table showing also the resource path i.e

```
index : GET controller/index
show : GET controller/1
destroy : DELETE controller/1
```

**Comment by tanner0101** [comment]
Check out https://docs.vapor.codes/2.0/vapor/controllers/#resources

**Comment by brunobl** [comment]
Unless I'm mistaken, documentation still hasn't changed about this issue.

For example, what is destroy precisely?
What is aboutMultiple? How to use it?

**Comment by superarts** [comment]
`destroy`, `aboutItem`, and `aboutMultiple` are not documented yet.

**Comment by pdesantis** [comment]
Agreed, I can't find any documentation on `destroy`, `aboutItem` and `aboutMultiple`. Should this issue be reopened?

**Comment by tanner0101** [comment]
Whoops, sorry about that. Fixed: https://docs.vapor.codes/2.0/vapor/controllers/#resources
