### ISSUE TITLE
ensure all `drop.middleware +=` are changed to config

### ISSUE THREAD

**Issue by tanner0101** [vapor/documentation#169]

**Comment by ankit1ank** [comment]
I have updated some here: https://github.com/vapor/documentation/pull/176

**Comment by tanner0101** [comment]
I fixed all I could find in https://github.com/vapor/documentation/commit/5110e9af92469744dd42cc435a102645ac31d7e2. Closing this issue for now. 

#176 remains opens with my comments. Thanks!
