### ISSUE TITLE
Outdated Validation section

### ISSUE THREAD

**Issue by Cellane** [vapor/documentation#189]
The Validation section of documentation is currently out of date so much that unless I'm doing something horribly wrong when it comes to the code, even the first snippet of code isn't applicable to the current version of the Validation package – I don't think the `Valid<Validator>` class is contained in the current version of package, is it?

At this point, I am afraid I'm not even sure how to start with this surely important package.

**Comment by tanner0101** [comment]
That documentation is indeed outdated. We're still working on that package though. There are a few important features that it's missing and it's likely to have another big re-write.

For now, if you'd like to use it, I'd recommend referencing the source code. Version 3.0 will be more feature complete and at that time it will make more sense to document it fully.
