### ISSUE TITLE
Protocol Model 

### ISSUE THREAD

**Issue by HC1058503505** [vapor/documentation#201]
In my opinion, your written document is too simple, can in detail, such as the use of the Leaf can write a detailed example of this.And feel a lot of places need to update, such as the Model should be obey the RowConvertible agreement now.But in the document or observe NodeInitializable and NodeRepresentable agreement.This is beginning to make me very confused, and learning together with difficulty.

**Comment by tanner0101** [comment]
Sorry that you were confused by the documentation. We try our best to write good documentation.  Please raise _specific_ problems about the documentation as separate GitHub issues. Otherwise it's very difficult to track and fix problems. Thanks :)

**Comment by HC1058503505** [comment]
Thank you for your answer.I have found the Vapor Docs at https://docs.vapor.codes/2.0/ , and problem has been resolved, found that the document is different with the document at GitHub, should be dead simple update not in time.Model of Fluent software section, for example, they said to implement different protocols.

1. Vapor Docs at https://docs.vapor.codes/2.0/ 
`init(row:Row) throws`
`func makeRow() throws ->Row`

2. Vapo Docs  at GitHub
`init(node: Node, in context: Context) throws`
`func makeNode(context: Context) throws -> Node`

**Comment by vzsg** [comment]
The docs at vapor.github.io is old enough to drink (around 1.0, I guess). Perhaps they could be simply deleted to reduce confusion, @tanner0101? Or replaced with a single link to the real docs?

**Comment by tanner0101** [comment]
Good idea @vzsg, fixed: https://vapor.github.io/documentation/asdf

**Comment by 0xTim** [comment]
If this is a 301 then this should also fix Google listings! 👍

**Comment by tanner0101** [comment]
@0xTim it's just a JS redirect. Do you know of any way to do a 301 redirect using HTML?

**Comment by vzsg** [comment]
I don't think that's possible, but instead of using JavaScript, you could use meta refresh to redirect.

**Comment by tanner0101** [comment]
@vzsg great idea. Updating it now.

**Comment by 0xTim** [comment]
Ah yeah, forgot it was a GitHub hosted page
