### ISSUE TITLE
JWT Documentation for Signers

### ISSUE THREAD

**Issue by anthonycastelli** [vapor/documentation#206]
It appears the example for JWT Signers is a bit outdated. https://github.com/vapor/documentation/blob/master/2.0/docs/jwt/overview.md#custom-signers. @tanner0101 and I had a conversation on slack https://qutheory.slack.com/archives/C0N6LGM0W/p1502385156074524 regarding how the signers should actually work. 

The current documentation shows 
```json
{
  "signers": [
    {
      "type": "rsa",
      "kid": "1234",
      "algorithm": "rs256",
      "key": "yourkeyhere"
    }
  ]
}
```

and it should be 
```json
{
  "signers": {
    "signer": {
      "type": "rsa",
      "kid": "1234",
      "algorithm": "rs256",
      "key": "yourkeyhere"
    }
  }
}
```

**Comment by tanner0101** [comment]
thanks! fixed.
