### ISSUE TITLE
Unable to install vapor

### ISSUE THREAD

**Issue by ashishguru1986** [vapor/documentation#225]
dyld: Library not loaded: @rpath/libswiftCoreFoundation.dylib
  Referenced from: /usr/local/bin/vapor
  Reason: image not found
Abort trap: 6

**Comment by vzsg** [comment]
There's a glitch in the currently released Vapor Toolbox 3.0.0. To work around it, install Xcode 9 to `/Application/Xcode.app`, and the error should go away.

**Comment by tanner0101** [comment]
this should be fixed in >= 3.0.1

**Comment by sforsethi** [comment]
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/bin/vapor
  Reason: image not found
zsh: abort      vapor --help
