### ISSUE TITLE
Documentation Async Routing

### ISSUE THREAD

**Issue by robert-joosen** [vapor/documentation#233]
https://github.com/vapor/documentation/blob/vapor3/3.0/docs/routing/async.md#asynchronous-routing

``let router: AsyncRouter = app.make(AsyncRouter.self)``
AsyncRouter = Router.self 
try app.make
AsyncRouter is not a valid type

``router.on(``
.on method needs to be .post, .update, .delete and .get etc

**Comment by vzsg** [comment]
I think you are approaching this at a completely wrong angle.
