### ISSUE TITLE
Edit links are broken for both 2.0 and 3.0

### ISSUE THREAD

**Issue by asoderman** [vapor/documentation#280]
This is probably two separate issues.

The 2.0 documentation links to the 3.0 folder on the master branch which leads to a 404. After looking at the documentation it looks like it just requires a redeploy as the edit uri appears to be correct. e.g. https://github.com/vapor/documentation/edit/master/3.0/docs/index.md taken from https://docs.vapor.codes/2.0/

The 3.0 edit uri was just incorrect. I'm about to send a PR to fix it.

**Comment by tanner0101** [comment]
These appear to be working now, thanks!
