### ISSUE TITLE
Homebrew install command fails

### ISSUE THREAD

**Issue by pe8ter** [vapor/documentation#316]
The docs use a bad instruction for installing Vapor via Homebrew:

https://github.com/vapor/documentation/blob/5c7762d89eb66eaa19884d27640770e26304f6af/3.0/docs/install/macos.md

This is the command from the link:

```bash
brew install vapor/tap/vapor
```

When running this, Homebrew fails because it tries to clone a nonexistent repository:

https://github.com/vapor/homebrew-cask

I'm not sure what the correct remedy is, if it's updating the Homebrew script or updating the instructions. I did follow the instructions from [Vapor Forums](https://www.vaporforums.io/thread/30) and those worked.

**Comment by 0xTim** [comment]
Hmm this should work, it always has in the past

**Comment by pe8ter** [comment]
I just tried the command on a different computer and it worked with no issue. I will close the issue because it seems to be a problem with my one particular machine and not Vapor itself.

I'll spend a few minutes tonight looking at what's different between the two computers and will report back if I get any more info.
