### ISSUE TITLE
Missing Fluent documentation for 3.0

### ISSUE THREAD

**Issue by joshsharp** [vapor/documentation#322]
As 3.0 has now been released, I'd love to take it for a spin. However, the page on Relations is still missing details and says "coming soon": https://docs.vapor.codes/3.0/fluent/relations/
Others under Fluent are similar, including Pivot, Transactions, and Database.

**Comment by tanner0101** [comment]
Fluent 3.0 has not been released yet, docs will come with the release. 👍

**Comment by joshsharp** [comment]
Ah apologies, I thought 3.0 being in the [releases](https://github.com/vapor/vapor/releases) meant it was released.

**Comment by 0xTim** [comment]
Vapor 3.0 has been released, Fluent 3.0 is yet to be finalised 🙂

**Comment by joshsharp** [comment]
Thanks for clarifying! Sorry to bother you some more, if you have the time I'd love to clarify: so when I create a new Vapor 3.0 project, does this use Fluent 3.0 or an earlier version? If it's an earlier version, where do I see the docs for the relevant Fluent version so I can work with it? I can't see any way to find earlier Fluent docs by browsing https://docs.vapor.codes/ — probably I'm just missing something, but if so then maybe others will too.

**Comment by 0xTim** [comment]
Yeah when you create a new Vapor 3.0 project it uses the Fluent 3.0 RC (you can see the versions in your Package.swift). Have a look at the tests for examples or https://github.com/raywenderlich/vapor-til for others. Also join Discord if you haven’t for help!

**Comment by joshsharp** [comment]
Aha, gotcha! (I totally should've looked at Package.swift, sorry.) I find it a bit confusing that a released project contains unreleased versions of dependencies, but I appreciate pointers on where to look for examples until the docs appear. Thank you!
