### ISSUE TITLE
[Styleguide] Clarify repository pattern

### ISSUE THREAD

**Issue by ar4s** [vapor/documentation#373]
First off, I would like to thank everyone involved in making this awesome documentation :)

I have problem with:
> Controllers should follow the thread-safe architecture when possible. This means passing necessary Services to the controller on initialization instead of making them in the routes.

And example below this paragraph:

    final class LoginViewController: RouteCollection {
    private let userRepository: UserRepository

        init(userRepository: UserRepository) {
             self.userRepository = userRepository
        }

        func boot(router: Router) throws {
            router.get("/login", use: login)
        }

        func login(req: Request) throws -> String {
            //use `self.userRepository`

            return ""
        }
    }

I have question: how to achieve this? How to passing `userRepository` to the controller via `init` if I create the controller in `routes.swift` (which it's called by ``configure`` function)?

Thanks in advance.

**Comment by mcdappdev** [comment]
Hi! Thanks for the kind words :) You can find examples of what you're looking for here:

1. https://github.com/gotranseo/template/blob/master/Sources/App/Setup/routes.swift
2. https://github.com/gotranseo/template/blob/master/Sources/App/Setup/configure.swift#L19

Number 2 is really important - make sure to call the function inside of a closure!
