### ISSUE TITLE
Repository Pattern + Generic Models + Authentication Framework

### ISSUE THREAD

**Issue by kdbertel** [vapor/documentation#374]
In the Style Guide, it says to use the Repository pattern so that you can go against different database types in different circumstances. It then says:

> However, this strategy requires extra work to make your models generic as they can no longer conform the the specific database model types

Which makes some degree of sense. It even provides an example for a repository for `User` objects that are for some reason not generic. But then in the Fluent>Models text, it attempts to provide an example of a generic `User`, with a generic protocol for the database to use. As near as I can tell from my own coding, this is necessary in order to use the `User` object with two different database types?

But then, in the documentation for the `Authentication` framework, it doesn't use generic `User` objects at all.

It feels to me like these are mutually not-entirely-consistent, and it would be nice to get a good, solid example in the docs of how to use the Authentication framework in such a way that people can use both e.g. SQLite for unit tests and PostgreSQL for production. Is there any good way of doing this?

**Comment by mcdappdev** [comment]
This is definitely something that should have a more concrete example, my apologies for the lack of foresight on that with the style guide. I'll try and put something together this weekend that I can share + amend the guide with.

**Comment by kdbertel** [comment]
Not particularly, because it doesn't show how to use the `GenericModelRespository` in a situation such as a controller that needs to have an instance of it hanging around. For example:

```
final class GenericModelController {
    let repository: GenericModelRepository
    init(repository: GenericModelRepository) {
        self.repository = repository
    }
}
```

This fails to compile because `Protocol 'GenericModelRepository' can only be used as a generic  constraint because it has Self or associated type requirements`, even without also creating a route to use the repository.

The problem is not making it generic in itself; it's using the generic form in other classes, such as routes or controllers, that will want to do logic against the objects returned from the repository.

It appears this issue raises its head even outside of using the `Auth` framework, but it's particularly problematic with the `Auth` framework because of wanting to do things like `let user = req.requireAuthentication)`.

**Comment by mcdappdev** [comment]
Ah, I see what you're saying now. I'm actually not sure about that. @tanner0101 Do you have any insight on this?

**Comment by emarashliev** [comment]
@mcdappdev could you please tell, how can I add siblings to generic model ?

**Comment by mcdappdev** [comment]
@kdbertel Per a conversation in Discord, this is the suggested solution to this problem:

```swift
struct User {
    let id: UUID
    let name: String
}

protocol UserRepository {
    func get(by id: UUID) -> Future<User>
}

class MySQLUserRepo: UserRepository {
    
    class UserMySQL: Model  {
        typealias Database = MySQLDatabase
        typealias ID = Int
        
        static var idKey: IDKey { return \.id }
        
        var id: Int?
        var name: String
    }
    
    func get(by id: UUID) -> Future<User> {
        return UserMySQL.find(by: id).map { user in
            return User(id: user.id!, name: user.name)
        }
    }
}
```

Let me know if that makes sense. Going to close this issue for now

**Comment by kdbertel** [comment]
So for every model object, I have to create a struct that's the actual model referred to by my controller etc., and then create a shadow struct that's the exact same structure for every database I'm using, and hope they don't get out of sync especially when it comes to things like migrations?

That then sounds like the section on making models generic to work with different Fluent providers needs to be rewritten.

Also, how does this work vis-à-vis the Authentication module?

**Comment by mcdappdev** [comment]
Yeah, it'll need some reworking. I think I'll probably also make a recommendation to create a `UserRepresentable` protocol to keep the properties in check. But this solution allows you to keep the data model fully separate from the persistence model.

Regarding Authentication, that has yet to be figured out as right now it's pretty engrained with Fluent

**Comment by kdbertel** [comment]
So it sounds like what I was wanting to do is not actually possible with the current state of things.

**Comment by mcdappdev** [comment]
Well, substituting out MySQL for SQLite should certainly be possible with the solution posted above. But the Authentication stuff has yet to be figured out. I guess right now you would have to rewrite the pieces of the auth system you need manually, which is, of course, not ideal haha
