### ISSUE TITLE
[Styleguide] App Configuration

### ISSUE THREAD

**Issue by gperdomor** [vapor/documentation#376]
As we know, environment variables are a crucial part of an app configuration, we can use to configure the database connection (when the app starts) or other things like the length of the access token.

Let's say that we can speak about two types of configuration, ones are used one time when the app starts, and the other kind are the used multiple times by some controllers to process the requests.

In the first case, we can use `Environment.get` to get the value, but in the second case, when I want to generate a token during login process, I should obtain the token length using `Environment.get` every time or I should create a service to store this values, and use that service to get the stored value?

Which are the pros and cons of both cases?

**Comment by mcdappdev** [comment]
My personal philosophy on this is to create a model object like `KeyStorage` that holds all of the values that you want to reference throughout your app. This makes it easier to swap out your credentials system if needed - for example, maybe you want to switch to using a JSON file for configuration instead, all you would need to do is update the parsing in `configure.swift` and the rest of your code remains the same. Make sense?

**Comment by mcdappdev** [comment]
Going to close this, feel free to reopen for more conversation.
