### ISSUE TITLE
Document using .env files locally

### ISSUE THREAD

**Issue by joscdk** [vapor/documentation#390]
Using .env files locally, is becoming more and more popular, so i think we should consider adding how to in the documentation, even though it's a vapor-community project.

This gist describes shortly how https://gist.github.com/joscdk/400567669ba5ed468467d0f1aebd9d36

(It is important to stress people need to add the file to .gitignore)

**Comment by mcdappdev** [comment]
Agreed, however I'm personally more in favor of something like this: https://gist.github.com/vzsg/ef79aebcd4716afc71c9c231c1ee0cbe. I don't know if it's smart to recommend pulling in an entire project full of extensions just to get the .env stuff. Thoughts?

**Comment by vzsg** [comment]
I agree that it would be cleaner to copy that [one file](https://github.com/vapor-community/vapor-ext/blob/master/Sources/ServiceExt/Environment%2BDotEnv.swift) from vapor-ext or my version from that gist above than adding a reference to the whole vapor-ext.

But for an end user, ultimately, it would be best if a version came with the framework itself...

**Comment by mcdappdev** [comment]
For sure. I would love to see a simple extension like that in Vapor 4

**Comment by joscdk** [comment]
Yeah i have said to @tanner0101 before this should be part of the Vapor core :D

**Comment by tanner0101** [comment]
Mind opening an issue on vapor/vapor to track that?

**Comment by joscdk** [comment]
@tanner0101 didn't see this before now.. https://github.com/vapor/vapor/issues/1885 .. Closing for now, once feature is implemented in Vapor we can open a new issue here.
