### ISSUE TITLE
How to use certificate in vapor 3?

### ISSUE THREAD

**Issue by v57** [vapor/documentation#395]
I want to set https certificate but i can't find any information on how to do that in vapor 3

**Comment by tanner0101** [comment]
Vapor 3 only supports plaintext HTTP. You'll want to add something like NGINX in front for TLS. The docs from Vapor 2 should help: https://docs.vapor.codes/2.0/deploy/nginx/

We definitely need to update those for Vapor 3. Sorry about that. 

FWIW, Vapor 4 will include TLS support.

**Comment by v57** [comment]
Thanks. Will vapor 4 come with swift 5?

**Comment by joscdk** [comment]
@v57 there isn't a specific date set yet .. However Vapor 4 will require Swift 5 and NIO 2.0 .. Meaning Vapor 4 will come after those :)

**Comment by v57** [comment]
Okay thank you so much. Such a nice community 💖
