### ISSUE TITLE
The lack of a dependent?

### ISSUE THREAD

**Issue by zhao95** [vapor/documentation#53]
when i do  
1.  let package = Package(
   name: "MyApp",
   dependencies: [
       .Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1, minor: 0),
       .Package(url: "https://github.com/vapor/mysql-provider.git", majorVersion: 1, minor: 0)
   ]
   )
2. vapor build
3. run xcode app

Display this : 

ld: library not found for -lCLibreSSL for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

How can I do? I'm a newbie... ...

**Comment by OliverWangHansen** [comment]
Hi,

Try open the terminale and run "vapor build --clean" and then afterwards "vapor xcode".
