### ISSUE TITLE
Clear documentation on Nodes

### ISSUE THREAD

**Issue by delta98** [vapor/documentation#57]
As a fundamental concept within Vapor, references to Node within the documentation (currently) assume an understanding in the context `node` is being used. 

I often find myself wanting to understand more around the concepts and transforms taking place between the request - to - backend representation of Node. 

Topics: NodeRepresentable, Node, makeNode

**Comment by tanner0101** [comment]
Check out https://docs.vapor.codes/2.0/json/overview/ and https://docs.vapor.codes/2.0/fluent/getting-started/#row.
